source 'https://rubygems.org'

# for the web APIs
gem 'thin'
gem 'sinatra'

# for the join and leave notifier
gem 'file-tail'
gem 'slack-notifier'

group :development do
  gem 'rerun'
  gem 'pry'
end
